spring:
    application.name: hello-spring
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: SPRING_BOOT
        password: 1234
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    # 파일 업로드 설정
    servlet:
        multipart:
            # 1024byte -> 1kb -> 1024kb 0> 1mb
            # 최대 업로드 파일 크기 설정 (100MB : 1024 * 1024 = 100), Mac(100MB : 1000 * 1000 = 100)
            max-file-size: 104857600
            # 요청당 최대 업로드 파일 크기 설정 (10MB : 1024 * 1024 * 10)
            max-request-size: 10485760

# classpath: Java, XML 이런 파일을 가지고 있는 프로젝트 정보들이 컴파일 되어 보관하는 경로.

# C:\dev_programs\sts_workspace\hello-spring\target\classes : classpath
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/hello/forum/**/dao/mapper/*Mapper.xml
app: 
    multipart:
        #파일 업로드 위치 지정
        base-dir: c:/uploadFiles
        # 난독화 여부 설정
        obfuscation:
            # 파일명 확장자 난독화를 할 경우 true
            enable: true
            # 파일 확장자 가리기 여부 설정
            hide-ext:
                # 파일 확장자 가질 경우 true
                enable: true
        # 확장자만 바꾸면 업로드가 가능해서 불안정하다. (이런 작업을 해야 안정적으로 웹 운영이 가능하다.)
        # List 는 - 로 구분한다.
        available-file-list:
            audio/aac,
            video/x-msvideo,
            text/css,
            text/csv,
            image/gif,
            text/html,
            application/msword,
            image/jpeg,
            application/json,
            audio/midi,
            video/mpeg,
            audio/ogg,
            video/ogg,
            application/ogg,
            application/pdf,
            application/vnd.ms-powerpoint,
            image/png,
            image/tiff,
            application/vnd.ms-excel,
            application/zip,
            application/vnd.openxmlformats-officedocument.wordprocessingml.document,
            application/vnd.openxmlformats-officedocument.presentationml.presentation,
            text/plain